# Generated by Django 6.0.4 on 2026-04-18 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Код (МКБ)")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Диагноз",
                "verbose_name_plural": "Диагнозы",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Код")),
                ("unit", models.CharField(blank=True, max_length=50, verbose_name="Единица измерения")),
                (
                    "type",
                    models.CharField(
                        choices=[("number", "Число"), ("boolean", "Да/Нет"), ("text", "Текст")],
                        max_length=50,
                        verbose_name="Тип значения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика",
                "verbose_name_plural": "Метрики",
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата записи")),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись дневника",
                "verbose_name_plural": "Записи дневника",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiaryEntryValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_number", models.FloatField(blank=True, null=True, verbose_name="Числовое значение")),
                ("value_text", models.TextField(blank=True, verbose_name="Текстовое значение")),
                ("value_boolean", models.BooleanField(blank=True, null=True, verbose_name="Булево значение")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="diagnoses.diaryentry",
                        verbose_name="Запись",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_values",
                        to="diagnoses.metric",
                        verbose_name="Метрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение метрики",
                "verbose_name_plural": "Значения метрик",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_required", models.BooleanField(default=False, verbose_name="Обязательная")),
                ("min_value", models.FloatField(blank=True, null=True, verbose_name="Минимум")),
                ("max_value", models.FloatField(blank=True, null=True, verbose_name="Максимум")),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="diagnoses.diagnosis",
                        verbose_name="Диагноз",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_metrics",
                        to="diagnoses.metric",
                        verbose_name="Метрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика диагноза",
                "verbose_name_plural": "Метрики диагнозов",
            },
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата назначения")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначил",
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_diagnoses",
                        to="diagnoses.diagnosis",
                        verbose_name="Диагноз",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диагноз пациента",
                "verbose_name_plural": "Диагнозы пациентов",
            },
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(fields=["patient", "-created_at"], name="diaryentry_patient_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="diaryentryvalue",
            unique_together={("entry", "metric")},
        ),
        migrations.AlterUniqueTogether(
            name="diagnosismetric",
            unique_together={("diagnosis", "metric")},
        ),
        migrations.AlterUniqueTogether(
            name="patientdiagnosis",
            unique_together={("patient", "diagnosis")},
        ),
    ]
