# Generated by Django 6.0.3 on 2026-04-15 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата последнего сообщения"),
                ),
                (
                    "participants",
                    models.ManyToManyField(related_name="chats", to=settings.AUTH_USER_MODEL, verbose_name="Участники"),
                ),
            ],
            options={
                "verbose_name": "Чат",
                "verbose_name_plural": "Чаты",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
    ]
