# Generated by Django 6.0.3 on 2026-04-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_legacy_chats(apps: object, schema_editor: object) -> None:
    """Удаляет чаты, созданные до появления поля patient.

    Старые чаты не привязаны к конкретному пациенту и несовместимы с новой моделью.
    Новые чаты будут созданы сигналами при перезагрузке данных.
    """
    Chat = apps.get_model("chats", "Chat")  # ty: ignore[unresolved-attribute]
    Chat.objects.all().delete()


class Migration(migrations.Migration):
    """Добавляет поле patient к чату и удаляет устаревшие чаты без контекста пациента."""

    # DELETE с каскадом по M2M и последующий ALTER TABLE несовместимы в одной транзакции в PostgreSQL
    atomic = False

    dependencies = [
        ("chats", "0003_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_legacy_chats, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="chat",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациент",
            ),
        ),
    ]
