# Generated by Django 6.0.3 on 2026-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_add_patient_to_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
    ]
