# Generated by Django 6.0.3 on 2026-04-14 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverPatient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата назначения")),
                (
                    "caregiver",
                    models.ForeignKey(
                        limit_choices_to={"role": "caregiver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Опекун",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_caregivers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь опекун-пациент",
                "verbose_name_plural": "Связи опекун-пациент",
                "unique_together": {("caregiver", "patient")},
            },
        ),
        migrations.CreateModel(
            name="DoctorPatient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата назначения")),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_doctors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь доктор-пациент",
                "verbose_name_plural": "Связи доктор-пациент",
                "unique_together": {("doctor", "patient")},
            },
        ),
    ]
