# Generated by Django 6.0.3 on 2026-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_doctor_patient_caregiver_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50, verbose_name="Часовой пояс"),
        ),
    ]
