# Generated by Django 6.0.3 on 2026-05-03 13:57

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diagnoses", "0002_diaryentry_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(0),
                                django.core.validators.MaxValueValidator(6),
                            ]
                        ),
                        verbose_name="Дни недели",
                    ),
                ),
                (
                    "times",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TimeField(), verbose_name="Время отправки"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Включено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notification_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["patient", "caregiver"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание уведомлений",
                "verbose_name_plural": "Расписания уведомлений",
                "unique_together": {("recipient", "patient")},
            },
        ),
        migrations.CreateModel(
            name="NotificationChannelConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("web_push", "Web Push")], max_length=20, verbose_name="Канал"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("config", models.JSONField(default=dict, verbose_name="Конфигурация канала")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channel_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал уведомлений",
                "verbose_name_plural": "Каналы уведомлений",
                "unique_together": {("user", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("web_push", "Web Push")], max_length=20, verbose_name="Канал"
                    ),
                ),
                ("channel_target", models.CharField(max_length=500, verbose_name="Адрес доставки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Отправлено"),
                            ("opened", "Открыто"),
                            ("completed", "Выполнено"),
                            ("ignored", "Проигнорировано"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("reaction_score", models.SmallIntegerField(blank=True, null=True, verbose_name="Оценка реакции")),
                ("sent_at", models.DateTimeField(auto_now_add=True, verbose_name="Отправлено")),
                ("opened_at", models.DateTimeField(blank=True, null=True, verbose_name="Открыто")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Выполнено")),
                ("metadata", models.JSONField(default=dict, verbose_name="Метаданные")),
                (
                    "diary_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_by",
                        to="diagnoses.diaryentry",
                        verbose_name="Запись дневника",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notification_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="notifications.notificationschedule",
                        verbose_name="Расписание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["recipient", "-sent_at"], name="notifrecord_recipient_sent_idx"),
                    models.Index(fields=["patient", "-sent_at"], name="notifrecord_patient_sent_idx"),
                    models.Index(fields=["status", "sent_at"], name="notifrecord_status_sent_idx"),
                ],
            },
        ),
    ]
